version: '3.1'

services:
  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aps-8-sem
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - ./mysql:/var/lib/mysql
